"""
Generates WordPress theme files from the AI analysis result and packages
them as an installable .zip file.
"""
import os
import re
import zipfile
from typing import Optional

import requests

_HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/124.0.0.0 Safari/537.36"
    )
}

_IMAGE_EXTS = (".jpg", ".jpeg", ".png", ".webp", ".gif", ".svg", ".bmp", ".ico", ".avif")


def build_theme_zip(analysis: dict, output_dir: str = ".") -> str:
    """
    Build a WordPress theme zip from the analysis result.
    Downloads images, generates PHP/CSS files, and packages everything.
    Returns the path to the created zip file.
    """
    theme_name = analysis.get("theme_name", "Custom Theme")
    theme_slug = _slugify(analysis.get("theme_slug", "custom-theme"))
    description = analysis.get("description", "Generated by WordPress Site Bot")
    global_css = analysis.get("global_css", "")
    header_html = analysis.get("header_html", "")
    body_html = analysis.get("body_html", "")
    footer_html = analysis.get("footer_html", "")

    # Filter to real image URLs only
    raw_images = analysis.get("images", [])
    images = [
        img for img in raw_images
        if any(img.get("original_url", "").lower().split("?")[0].endswith(ext) for ext in _IMAGE_EXTS)
    ]

    # Download images
    image_data: dict[str, bytes] = {}   # filename -> raw bytes
    image_map: dict[str, str] = {}      # placeholder_id -> filename

    for img in images:
        placeholder_id = img.get("placeholder_id", "")
        filename = img.get("filename", "")
        original_url = img.get("original_url", "")
        if not all([placeholder_id, filename, original_url]):
            continue
        try:
            resp = requests.get(original_url, headers=_HEADERS, timeout=20, stream=True)
            resp.raise_for_status()
            data = b"".join(resp.iter_content(chunk_size=8192))
            image_data[filename] = data
            image_map[placeholder_id] = filename
            print(f"[theme] Downloaded: {filename}")
        except Exception as e:
            print(f"[theme] WARNING: Could not download {original_url}: {e}")

    # Replace image placeholders with PHP theme directory URI in all HTML fields
    for placeholder_id, filename in image_map.items():
        php_uri = f"<?php echo get_template_directory_uri(); ?>/images/{filename}"
        header_html = header_html.replace(f"__IMG_{placeholder_id}__", php_uri)
        body_html   = body_html.replace(f"__IMG_{placeholder_id}__", php_uri)
        footer_html = footer_html.replace(f"__IMG_{placeholder_id}__", php_uri)

    # Extract Customizer fields then replace markers with PHP get_theme_mod() calls
    customizer_fields = _extract_customizer_fields(header_html + body_html + footer_html)
    header_html = _replace_customizer_markers(header_html)
    body_html   = _replace_customizer_markers(body_html)
    footer_html = _replace_customizer_markers(footer_html)

    # Generate theme files
    files = {
        "style.css":      _style_css(theme_name, theme_slug, description, global_css),
        "functions.php":  _functions_php(theme_slug, customizer_fields),
        "header.php":     _header_php(header_html),
        "footer.php":     _footer_php(footer_html),
        "index.php":      _index_php(),
        "page.php":       _page_php(),
        "front-page.php": _front_page_php(body_html),
        "single.php":     _single_php(),
        "archive.php":    _archive_php(),
        "home.php":       _home_php(),
    }

    # Write theme files to disk (so the editor can read/modify them)
    theme_dir = os.path.join(output_dir, theme_slug)
    os.makedirs(theme_dir, exist_ok=True)
    images_dir = os.path.join(theme_dir, "images")
    os.makedirs(images_dir, exist_ok=True)

    for filename, content in files.items():
        with open(os.path.join(theme_dir, filename), "w", encoding="utf-8") as f:
            f.write(content)
        print(f"[theme] Saved: {filename}")
    for filename, data in image_data.items():
        with open(os.path.join(images_dir, filename), "wb") as f:
            f.write(data)
        print(f"[theme] Saved: images/{filename}")

    # Save theme metadata for use by add_page.py
    import json as _json
    meta = {
        "theme_name":      theme_name,
        "theme_slug":      theme_slug,
        "primary_color":   analysis.get("primary_color", ""),
        "secondary_color": analysis.get("secondary_color", ""),
        "accent_color":    analysis.get("accent_color", ""),
    }
    with open(os.path.join(theme_dir, "theme-meta.json"), "w", encoding="utf-8") as f:
        _json.dump(meta, f, indent=2)

    # Package zip from the on-disk folder
    zip_path = _zip_theme_dir(theme_dir, output_dir, theme_slug)
    print(f"[theme] Created: {zip_path}")
    return zip_path


def rezip_theme(theme_dir: str) -> str:
    """Re-package an existing theme folder into a zip. Returns zip path."""
    theme_dir = os.path.abspath(theme_dir)
    theme_slug = os.path.basename(theme_dir)
    output_dir = os.path.dirname(theme_dir)
    return _zip_theme_dir(theme_dir, output_dir, theme_slug)


def _zip_theme_dir(theme_dir: str, output_dir: str, theme_slug: str) -> str:
    zip_path = os.path.join(output_dir, f"{theme_slug}.zip")
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for root, _, filenames in os.walk(theme_dir):
            for filename in filenames:
                full_path = os.path.join(root, filename)
                arcname = os.path.join(theme_slug, os.path.relpath(full_path, theme_dir))
                zf.write(full_path, arcname)
    return zip_path


# ── Template generators ────────────────────────────────────────────────────────

def _style_css(theme_name: str, theme_slug: str, description: str, global_css: str) -> str:
    return f"""/*
Theme Name: {theme_name}
Theme URI: https://automai.ai
Author: WordPress Site Bot
Author URI: https://automai.ai
Description: {description}
Version: 1.0.0
Requires at least: 6.0
Tested up to: 6.7
License: GNU General Public License v2 or later
License URI: https://www.gnu.org/licenses/gpl-2.0.html
Text Domain: {theme_slug}
*/

/* ── Reset & Base ── */
*, *::before, *::after {{
    box-sizing: border-box;
    margin: 0;
    padding: 0;
}}
html {{
    scroll-behavior: smooth;
}}
body {{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
    line-height: 1.6;
    color: #1a1a1a;
    -webkit-font-smoothing: antialiased;
}}
img {{
    max-width: 100%;
    height: auto;
    display: block;
}}
a {{
    text-decoration: none;
    color: inherit;
}}

/* ── Global Styles (from AI) ── */
{global_css}
"""


def _functions_php(theme_slug: str, customizer_fields: Optional[list] = None) -> str:
    fn = theme_slug.replace("-", "_")
    customizer_fields = customizer_fields or []

    # Build Customizer registration PHP
    if customizer_fields:
        field_registrations = []
        for field in customizer_fields:
            name    = field["name"]
            default = field["default"].replace("'", "\\'")
            label   = field["label"]
            field_registrations.append(f"""
    $wp_customize->add_setting( '{name}', array(
        'default'           => '{default}',
        'sanitize_callback' => 'sanitize_text_field',
        'transport'         => 'refresh',
    ) );
    $wp_customize->add_control( '{name}', array(
        'label'   => '{label}',
        'section' => '{fn}_content',
        'type'    => 'text',
    ) );""")

        customizer_block = f"""
function {fn}_customize_register( $wp_customize ) {{
    $wp_customize->add_section( '{fn}_content', array(
        'title'    => 'Site Content',
        'priority' => 30,
    ) );
{''.join(field_registrations)}
}}
add_action( 'customize_register', '{fn}_customize_register' );
"""
    else:
        customizer_block = ""

    return f"""<?php
/**
 * {theme_slug} functions and definitions
 */

function {fn}_setup() {{
    add_theme_support( 'title-tag' );
    add_theme_support( 'post-thumbnails' );
    add_theme_support( 'responsive-embeds' );
    add_theme_support( 'html5', array(
        'search-form', 'comment-form', 'comment-list',
        'gallery', 'caption', 'style', 'script'
    ) );
}}
add_action( 'after_setup_theme', '{fn}_setup' );

function {fn}_scripts() {{
    wp_enqueue_style(
        '{theme_slug}-style',
        get_stylesheet_uri(),
        array(),
        '1.0.0'
    );
}}
add_action( 'wp_enqueue_scripts', '{fn}_scripts' );
{customizer_block}"""


def _header_php(header_html: str) -> str:
    return f"""<!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
    <meta charset="<?php bloginfo( 'charset' ); ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="profile" href="https://gmpg.org/xfn/11">
    <?php wp_head(); ?>
</head>
<body <?php body_class(); ?>>
<?php wp_body_open(); ?>
{header_html}
"""


def _footer_php(footer_html: str) -> str:
    return f"""{footer_html}
<?php wp_footer(); ?>
</body>
</html>
"""


def _index_php() -> str:
    return """<?php
/**
 * The main template file.
 * Fallback when no other template matches.
 */
get_header();
?>
<main id="main" style="min-height:60vh;">
    <?php
    if ( have_posts() ) :
        while ( have_posts() ) :
            the_post();
            the_content();
        endwhile;
    endif;
    ?>
</main>
<?php
get_footer();
"""


def _page_php() -> str:
    return """<?php
/**
 * The page template.
 * Used for all standard WordPress pages.
 * Content manages its own layout (no width constraint here).
 */
get_header();
?>
<main id="main" style="min-height:60vh;">
    <?php
    if ( have_posts() ) :
        while ( have_posts() ) :
            the_post();
            the_content();
        endwhile;
    endif;
    ?>
</main>
<?php
get_footer();
"""


def _front_page_php(body_html: str) -> str:
    return f"""<?php
/**
 * The front page template.
 * Homepage content — hero, services, CTA, etc.
 */
get_header();
?>
{body_html}
<?php
get_footer();
"""


def _single_php() -> str:
    return """<?php
/**
 * The single post template.
 * Used for individual blog posts.
 */
get_header();
?>
<main id="main" style="padding:80px 0;min-height:60vh;">
  <div class="container" style="max-width:780px;">
    <?php while ( have_posts() ) : the_post(); ?>

    <article <?php post_class(); ?>>

      <?php if ( has_post_thumbnail() ) : ?>
        <div style="margin-bottom:40px;border-radius:12px;overflow:hidden;">
          <?php the_post_thumbnail( 'full', array( 'style' => 'width:100%;height:420px;object-fit:cover;display:block;' ) ); ?>
        </div>
      <?php endif; ?>

      <header style="margin-bottom:40px;">
        <div style="display:flex;align-items:center;gap:12px;font-size:13px;color:#888;margin-bottom:16px;flex-wrap:wrap;">
          <span><?php echo esc_html( get_the_date() ); ?></span>
          <span style="opacity:0.4;">·</span>
          <span><?php the_author(); ?></span>
          <?php
          $cats = get_the_category();
          if ( $cats ) :
          ?>
          <span style="opacity:0.4;">·</span>
          <span style="background:var(--color-primary,#333);color:#fff;padding:3px 10px;border-radius:20px;font-size:12px;font-weight:600;">
            <?php echo esc_html( $cats[0]->name ); ?>
          </span>
          <?php endif; ?>
        </div>
        <h1 style="font-size:clamp(28px,5vw,46px);font-weight:800;line-height:1.2;color:var(--color-secondary,#1a1a1a);">
          <?php the_title(); ?>
        </h1>
      </header>

      <div class="entry-content" style="font-size:17px;line-height:1.8;color:#333;">
        <?php the_content(); ?>
      </div>

      <footer style="margin-top:60px;padding-top:32px;border-top:1px solid #eee;">
        <?php
        $tags = get_the_tags();
        if ( $tags ) : ?>
          <div style="display:flex;flex-wrap:wrap;gap:8px;margin-bottom:28px;">
            <?php foreach ( $tags as $tag ) : ?>
              <a href="<?php echo esc_url( get_tag_link( $tag ) ); ?>"
                 style="background:#f0f0f0;padding:4px 12px;border-radius:20px;font-size:13px;color:#555;transition:background 0.2s;"
                 onmouseover="this.style.background='var(--color-primary,#333)';this.style.color='#fff'"
                 onmouseout="this.style.background='#f0f0f0';this.style.color='#555'">
                #<?php echo esc_html( $tag->name ); ?>
              </a>
            <?php endforeach; ?>
          </div>
        <?php endif; ?>

        <div style="display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap;">
          <?php
          $prev = get_previous_post();
          $next = get_next_post();
          ?>
          <?php if ( $prev ) : ?>
            <a href="<?php echo esc_url( get_permalink( $prev ) ); ?>"
               style="flex:1;min-width:180px;padding:20px;border:1px solid #eee;border-radius:10px;font-size:14px;color:var(--color-primary,#333);transition:border-color 0.2s;"
               onmouseover="this.style.borderColor='var(--color-primary,#333)'"
               onmouseout="this.style.borderColor='#eee'">
              <div style="font-size:11px;text-transform:uppercase;letter-spacing:.08em;opacity:.5;margin-bottom:6px;">← Previous</div>
              <strong><?php echo esc_html( get_the_title( $prev ) ); ?></strong>
            </a>
          <?php endif; ?>
          <?php if ( $next ) : ?>
            <a href="<?php echo esc_url( get_permalink( $next ) ); ?>"
               style="flex:1;min-width:180px;padding:20px;border:1px solid #eee;border-radius:10px;text-align:right;font-size:14px;color:var(--color-primary,#333);transition:border-color 0.2s;"
               onmouseover="this.style.borderColor='var(--color-primary,#333)'"
               onmouseout="this.style.borderColor='#eee'">
              <div style="font-size:11px;text-transform:uppercase;letter-spacing:.08em;opacity:.5;margin-bottom:6px;">Next →</div>
              <strong><?php echo esc_html( get_the_title( $next ) ); ?></strong>
            </a>
          <?php endif; ?>
        </div>
      </footer>

    </article>

    <?php endwhile; ?>
  </div>
</main>
<?php
get_footer();
"""


def _archive_php() -> str:
    return """<?php
/**
 * The archive / blog index template.
 * Used for the Blog page, category pages, tag pages, date archives, etc.
 */
get_header();
?>
<main id="main" style="padding:80px 0;min-height:60vh;">
  <div class="container">

    <header style="text-align:center;margin-bottom:64px;">
      <?php if ( is_category() ) : ?>
        <p class="section-label" style="color:var(--color-primary,#333);">Category</p>
        <h1 class="section-title"><?php single_cat_title(); ?></h1>
        <?php if ( category_description() ) : ?>
          <p style="color:#666;max-width:540px;margin:16px auto 0;line-height:1.7;"><?php echo category_description(); ?></p>
        <?php endif; ?>
      <?php elseif ( is_tag() ) : ?>
        <p class="section-label" style="color:var(--color-primary,#333);">Tag</p>
        <h1 class="section-title"><?php single_tag_title(); ?></h1>
      <?php elseif ( is_author() ) : ?>
        <p class="section-label" style="color:var(--color-primary,#333);">Author</p>
        <h1 class="section-title"><?php the_author(); ?></h1>
      <?php else : ?>
        <p class="section-label" style="color:var(--color-primary,#333);">Our Blog</p>
        <h1 class="section-title"><?php bloginfo( 'name' ); ?> — Latest Posts</h1>
      <?php endif; ?>
    </header>

    <?php if ( have_posts() ) : ?>
      <div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(300px,1fr));gap:32px;">
        <?php while ( have_posts() ) : the_post(); ?>

          <article <?php post_class( 'blog-card' ); ?>
                   style="background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 2px 20px rgba(0,0,0,0.07);transition:transform .2s,box-shadow .2s;display:flex;flex-direction:column;"
                   onmouseover="this.style.transform='translateY(-4px)';this.style.boxShadow='0 8px 32px rgba(0,0,0,0.12)'"
                   onmouseout="this.style.transform='';this.style.boxShadow='0 2px 20px rgba(0,0,0,0.07)'">

            <?php if ( has_post_thumbnail() ) : ?>
              <a href="<?php the_permalink(); ?>" style="display:block;overflow:hidden;height:200px;">
                <?php the_post_thumbnail( 'medium_large', array(
                  'style' => 'width:100%;height:100%;object-fit:cover;transition:transform .4s;',
                  'onmouseover' => "this.style.transform='scale(1.04)'",
                  'onmouseout'  => "this.style.transform='scale(1)'"
                ) ); ?>
              </a>
            <?php else : ?>
              <a href="<?php the_permalink(); ?>"
                 style="display:block;height:200px;background:var(--color-primary,#333);display:flex;align-items:center;justify-content:center;">
                <span style="font-size:48px;opacity:.3;">📝</span>
              </a>
            <?php endif; ?>

            <div style="padding:28px;flex:1;display:flex;flex-direction:column;">
              <div style="font-size:12px;color:#999;margin-bottom:12px;">
                <?php echo esc_html( get_the_date() ); ?>
                <?php
                $cats = get_the_category();
                if ( $cats ) : ?>
                  &nbsp;·&nbsp;
                  <a href="<?php echo esc_url( get_category_link( $cats[0]->term_id ) ); ?>"
                     style="color:var(--color-primary,#333);font-weight:600;">
                    <?php echo esc_html( $cats[0]->name ); ?>
                  </a>
                <?php endif; ?>
              </div>

              <h2 style="font-size:20px;font-weight:700;line-height:1.35;margin-bottom:12px;color:var(--color-secondary,#1a1a1a);">
                <a href="<?php the_permalink(); ?>"
                   style="color:inherit;transition:color .2s;"
                   onmouseover="this.style.color='var(--color-primary,#333)'"
                   onmouseout="this.style.color='inherit'">
                  <?php the_title(); ?>
                </a>
              </h2>

              <p style="color:#666;font-size:15px;line-height:1.7;flex:1;">
                <?php echo wp_trim_words( get_the_excerpt(), 22, '…' ); ?>
              </p>

              <a href="<?php the_permalink(); ?>"
                 class="btn btn-primary"
                 style="margin-top:20px;display:inline-block;text-align:center;">
                Read More
              </a>
            </div>

          </article>

        <?php endwhile; ?>
      </div>

      <div style="margin-top:64px;display:flex;justify-content:center;gap:8px;">
        <?php
        the_posts_pagination( array(
          'mid_size'           => 2,
          'prev_text'          => '← Newer',
          'next_text'          => 'Older →',
          'before_page_number' => '',
        ) );
        ?>
      </div>

    <?php else : ?>
      <div style="text-align:center;padding:80px 0;color:#999;">
        <div style="font-size:56px;margin-bottom:24px;">📭</div>
        <h2 style="font-size:24px;font-weight:600;margin-bottom:12px;color:#555;">No posts yet</h2>
        <p>Check back soon for new content.</p>
      </div>
    <?php endif; ?>

  </div>
</main>
<?php
get_footer();
"""


def _home_php() -> str:
    return """<?php
/**
 * home.php — Blog / posts pillar listing page.
 * WordPress uses this when a static front page is set and a Posts page
 * is configured under Settings → Reading.
 * Lists all posts newest-first with pagination.
 */
get_header();
?>
<main id="main" style="padding:80px 0;min-height:60vh;">
  <div class="container">

    <header style="text-align:center;margin-bottom:64px;">
      <p class="section-label" style="color:var(--color-primary,#333);">Our Blog</p>
      <h1 class="section-title"><?php bloginfo( 'name' ); ?> — Latest Posts</h1>
    </header>

    <?php if ( have_posts() ) : ?>
      <div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(300px,1fr));gap:32px;">
        <?php while ( have_posts() ) : the_post(); ?>

          <article <?php post_class(); ?>
                   style="background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 2px 20px rgba(0,0,0,0.07);transition:transform .2s,box-shadow .2s;display:flex;flex-direction:column;"
                   onmouseover="this.style.transform='translateY(-4px)';this.style.boxShadow='0 8px 32px rgba(0,0,0,0.12)'"
                   onmouseout="this.style.transform='';this.style.boxShadow='0 2px 20px rgba(0,0,0,0.07)'">

            <?php if ( has_post_thumbnail() ) : ?>
              <a href="<?php the_permalink(); ?>" style="display:block;overflow:hidden;height:200px;">
                <?php the_post_thumbnail( 'medium_large', array( 'style' => 'width:100%;height:100%;object-fit:cover;', 'loading' => 'lazy' ) ); ?>
              </a>
            <?php else : ?>
              <a href="<?php the_permalink(); ?>"
                 style="display:block;height:200px;background:var(--color-primary,#333);display:flex;align-items:center;justify-content:center;">
                <span style="font-size:48px;opacity:.3;">📝</span>
              </a>
            <?php endif; ?>

            <div style="padding:28px;flex:1;display:flex;flex-direction:column;">
              <div style="font-size:12px;color:#999;margin-bottom:12px;">
                <?php echo esc_html( get_the_date() ); ?>
                <?php $cats = get_the_category(); if ( $cats ) : ?>
                  &nbsp;·&nbsp;
                  <a href="<?php echo esc_url( get_category_link( $cats[0]->term_id ) ); ?>"
                     style="color:var(--color-primary,#333);font-weight:600;">
                    <?php echo esc_html( $cats[0]->name ); ?>
                  </a>
                <?php endif; ?>
              </div>

              <h2 style="font-size:20px;font-weight:700;line-height:1.35;margin-bottom:12px;color:var(--color-secondary,#1a1a1a);">
                <a href="<?php the_permalink(); ?>"
                   style="color:inherit;transition:color .2s;"
                   onmouseover="this.style.color='var(--color-primary,#333)'"
                   onmouseout="this.style.color='inherit'">
                  <?php the_title(); ?>
                </a>
              </h2>

              <p style="color:#666;font-size:15px;line-height:1.7;flex:1;">
                <?php echo wp_trim_words( get_the_excerpt(), 22, '…' ); ?>
              </p>

              <a href="<?php the_permalink(); ?>"
                 class="btn btn-primary"
                 style="margin-top:20px;display:inline-block;text-align:center;">
                Read More
              </a>
            </div>

          </article>

        <?php endwhile; ?>
      </div>

      <div style="margin-top:64px;display:flex;justify-content:center;gap:8px;">
        <?php
        the_posts_pagination( array(
          'mid_size'  => 2,
          'prev_text' => '← Newer',
          'next_text' => 'Older →',
        ) );
        ?>
      </div>

    <?php else : ?>
      <div style="text-align:center;padding:80px 0;color:#999;">
        <div style="font-size:56px;margin-bottom:24px;">📭</div>
        <h2 style="font-size:24px;font-weight:600;margin-bottom:12px;color:#555;">No posts yet</h2>
        <p>Check back soon for new content.</p>
      </div>
    <?php endif; ?>

  </div>
</main>
<?php
get_footer();
"""


# ── Helpers ───────────────────────────────────────────────────────────────────

def _extract_customizer_fields(html: str) -> list[dict]:
    """Extract {{field_name|default}} markers and return list of field dicts."""
    seen: set[str] = set()
    fields: list[dict] = []
    for name, default in re.findall(r'\{\{([a-z0-9_]+)\|([^}]*)\}\}', html):
        if name not in seen:
            seen.add(name)
            fields.append({
                "name":    name,
                "default": default,
                "label":   name.replace("_", " ").title(),
            })
    return fields


def _replace_customizer_markers(html: str) -> str:
    """Replace {{field_name|default}} with PHP get_theme_mod() calls."""
    def replacer(m: re.Match) -> str:
        name    = m.group(1)
        default = m.group(2).replace("'", "\\'")
        return f"<?php echo esc_html( get_theme_mod( '{name}', '{default}' ) ); ?>"
    return re.sub(r'\{\{([a-z0-9_]+)\|([^}]*)\}\}', replacer, html)


def _slugify(text: str) -> str:
    """Convert text to a filesystem-safe WordPress theme slug."""
    text = text.lower().strip()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[\s_]+", "-", text)
    text = re.sub(r"-{2,}", "-", text)
    text = re.sub(r"^-+|-+$", "", text)
    return text or "custom-theme"
