"""
Generates WordPress theme files from the AI analysis result and packages
them as an installable .zip file.
"""
import os
import re
import zipfile

import requests

_HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/124.0.0.0 Safari/537.36"
    )
}

_IMAGE_EXTS = (".jpg", ".jpeg", ".png", ".webp", ".gif", ".svg", ".bmp", ".ico", ".avif")


def build_theme_zip(analysis: dict, output_dir: str = ".") -> str:
    """
    Build a WordPress theme zip from the analysis result.
    Downloads images, generates PHP/CSS files, and packages everything.
    Returns the path to the created zip file.
    """
    theme_name = analysis.get("theme_name", "Custom Theme")
    theme_slug = _slugify(analysis.get("theme_slug", "custom-theme"))
    description = analysis.get("description", "Generated by WordPress Site Bot")
    global_css = analysis.get("global_css", "")
    header_html = analysis.get("header_html", "")
    body_html = analysis.get("body_html", "")
    footer_html = analysis.get("footer_html", "")

    # Filter to real image URLs only
    raw_images = analysis.get("images", [])
    images = [
        img for img in raw_images
        if any(img.get("original_url", "").lower().split("?")[0].endswith(ext) for ext in _IMAGE_EXTS)
    ]

    # Download images
    image_data: dict[str, bytes] = {}   # filename -> raw bytes
    image_map: dict[str, str] = {}      # placeholder_id -> filename

    for img in images:
        placeholder_id = img.get("placeholder_id", "")
        filename = img.get("filename", "")
        original_url = img.get("original_url", "")
        if not all([placeholder_id, filename, original_url]):
            continue
        try:
            resp = requests.get(original_url, headers=_HEADERS, timeout=20, stream=True)
            resp.raise_for_status()
            data = b"".join(resp.iter_content(chunk_size=8192))
            image_data[filename] = data
            image_map[placeholder_id] = filename
            print(f"[theme] Downloaded: {filename}")
        except Exception as e:
            print(f"[theme] WARNING: Could not download {original_url}: {e}")

    # Replace image placeholders with PHP theme directory URI in all HTML fields
    for placeholder_id, filename in image_map.items():
        php_uri = f"<?php echo get_template_directory_uri(); ?>/images/{filename}"
        header_html = header_html.replace(f"__IMG_{placeholder_id}__", php_uri)
        body_html   = body_html.replace(f"__IMG_{placeholder_id}__", php_uri)
        footer_html = footer_html.replace(f"__IMG_{placeholder_id}__", php_uri)

    # Generate theme files
    files = {
        "style.css":      _style_css(theme_name, theme_slug, description, global_css),
        "functions.php":  _functions_php(theme_slug),
        "header.php":     _header_php(header_html),
        "footer.php":     _footer_php(footer_html),
        "index.php":      _index_php(),
        "page.php":       _page_php(),
        "front-page.php": _front_page_php(body_html),
    }

    # Package zip
    zip_filename = f"{theme_slug}.zip"
    zip_path = os.path.join(output_dir, zip_filename)

    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for filename, content in files.items():
            zf.writestr(f"{theme_slug}/{filename}", content)
            print(f"[theme] Packed: {filename}")
        for filename, data in image_data.items():
            zf.writestr(f"{theme_slug}/images/{filename}", data)
            print(f"[theme] Packed: images/{filename}")

    print(f"[theme] Created: {zip_path}")
    return zip_path


# ── Template generators ────────────────────────────────────────────────────────

def _style_css(theme_name: str, theme_slug: str, description: str, global_css: str) -> str:
    return f"""/*
Theme Name: {theme_name}
Theme URI: https://automai.ai
Author: WordPress Site Bot
Author URI: https://automai.ai
Description: {description}
Version: 1.0.0
Requires at least: 6.0
Tested up to: 6.7
License: GNU General Public License v2 or later
License URI: https://www.gnu.org/licenses/gpl-2.0.html
Text Domain: {theme_slug}
*/

/* ── Reset & Base ── */
*, *::before, *::after {{
    box-sizing: border-box;
    margin: 0;
    padding: 0;
}}
html {{
    scroll-behavior: smooth;
}}
body {{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
    line-height: 1.6;
    color: #1a1a1a;
    -webkit-font-smoothing: antialiased;
}}
img {{
    max-width: 100%;
    height: auto;
    display: block;
}}
a {{
    text-decoration: none;
    color: inherit;
}}

/* ── Global Styles (from AI) ── */
{global_css}
"""


def _functions_php(theme_slug: str) -> str:
    fn = theme_slug.replace("-", "_")
    return f"""<?php
/**
 * {theme_slug} functions and definitions
 */

function {fn}_setup() {{
    add_theme_support( 'title-tag' );
    add_theme_support( 'post-thumbnails' );
    add_theme_support( 'responsive-embeds' );
    add_theme_support( 'html5', array(
        'search-form', 'comment-form', 'comment-list',
        'gallery', 'caption', 'style', 'script'
    ) );
}}
add_action( 'after_setup_theme', '{fn}_setup' );

function {fn}_scripts() {{
    wp_enqueue_style(
        '{theme_slug}-style',
        get_stylesheet_uri(),
        array(),
        '1.0.0'
    );
}}
add_action( 'wp_enqueue_scripts', '{fn}_scripts' );
"""


def _header_php(header_html: str) -> str:
    return f"""<!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
    <meta charset="<?php bloginfo( 'charset' ); ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="profile" href="https://gmpg.org/xfn/11">
    <?php wp_head(); ?>
</head>
<body <?php body_class(); ?>>
<?php wp_body_open(); ?>
{header_html}
"""


def _footer_php(footer_html: str) -> str:
    return f"""{footer_html}
<?php wp_footer(); ?>
</body>
</html>
"""


def _index_php() -> str:
    return """<?php
/**
 * The main template file.
 * Fallback when no other template matches.
 */
get_header();
?>
<main id="main" style="min-height:60vh;">
    <?php
    if ( have_posts() ) :
        while ( have_posts() ) :
            the_post();
            the_content();
        endwhile;
    endif;
    ?>
</main>
<?php
get_footer();
"""


def _page_php() -> str:
    return """<?php
/**
 * The page template.
 * Used for all standard WordPress pages.
 * Content manages its own layout (no width constraint here).
 */
get_header();
?>
<main id="main" style="min-height:60vh;">
    <?php
    if ( have_posts() ) :
        while ( have_posts() ) :
            the_post();
            the_content();
        endwhile;
    endif;
    ?>
</main>
<?php
get_footer();
"""


def _front_page_php(body_html: str) -> str:
    return f"""<?php
/**
 * The front page template.
 * Homepage content — hero, services, CTA, etc.
 */
get_header();
?>
{body_html}
<?php
get_footer();
"""


# ── Helpers ───────────────────────────────────────────────────────────────────

def _slugify(text: str) -> str:
    """Convert text to a filesystem-safe WordPress theme slug."""
    text = text.lower().strip()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[\s_]+", "-", text)
    text = re.sub(r"-{2,}", "-", text)
    text = re.sub(r"^-+|-+$", "", text)
    return text or "custom-theme"
